### ISSUE TITLE
Bad Strand Mapping Stat

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio#1167]
```
ta-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod 2019-03-21 21:22:21,103 i-04f994c9abb658f9e [volume: 9] data_refinery_workers.processors.utils ERROR [processor_job: 2101316] [no_retry: False]: Unhandled exception caught while running processor function _run_salmon in pipeline:
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod Traceback (most recent call last):
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 85, in _execute
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod     return self.cursor.execute(sql, params)
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod psycopg2.DataError: invalid input syntax for type json
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod LINE 1: ..., "created_at", "last_modified") VALUES (1044248, '{"compati...
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod                                                              ^
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod DETAIL:  Token "NaN" is invalid.
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod CONTEXT:  JSON data, line 1: ..._fragment_ratio": 1.0, "strand_mapping_bias": NaN...
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod The above exception was the direct cause of the following exception:
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod Traceback (most recent call last):
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod   File "/home/user/data_refinery_workers/processors/utils.py", line 482, in run_pipeline
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod     last_result = processor(last_result)
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod   File "/home/user/data_refinery_workers/processors/salmon.py", line 982, in _run_salmon
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod     kv.save()
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/data_refinery_common/models/models.py", line 549, in save
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod     return super(ComputationalResultAnnotation, self).save(*args, **kwargs)
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 718, in save
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod     force_update=force_update, update_fields=update_fields)
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 748, in save_base
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod     updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 831, in _save_table
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 869, in _do_insert
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod     using=using, raw=raw)
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/models/manager.py", line 82, in manager_method
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod     return getattr(self.get_queryset(), name)(*args, **kwargs)
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 1136, in _insert
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod     return query.get_compiler(using=using).execute_sql(return_id)
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/models/sql/compiler.py", line 1289, in execute_sql
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod     cursor.execute(sql, params)
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/raven/contrib/django/client.py", line 127, in execute
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod     return real_execute(self, sql, params)
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 68, in execute
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod     return executor(sql, params, many, context)
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 85, in _execute
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod     return self.cursor.execute(sql, params)
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/utils.py", line 89, in __exit__
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod     raise dj_exc_value.with_traceback(traceback) from exc_value
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 85, in _execute
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod     return self.cursor.execute(sql, params)
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod django.db.utils.DataError: invalid input syntax for type json
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod LINE 1: ..., "created_at", "last_modified") VALUES (1044248, '{"compati...
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod                                                              ^
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod DETAIL:  Token "NaN" is invalid.
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod CONTEXT:  JSON data, line 1: ..._fragment_ratio": 1.0, "strand_mapping_bias": NaN...
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod 2019-03-21 21:22:24,459 i-04f994c9abb658f9e [volume: 9] data_refinery_workers.processors.utils ERROR [processor_job: 2101316] [failure_reason: Unhandled exception caught while running processor function _run_salmon in pipeline: invalid input syntax for type json
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod LINE 1: ..., "created_at", "last_modified") VALUES (1044248, '{"compati...
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod                                                              ^
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod DETAIL:  Token "NaN" is invalid.
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod CONTEXT:  JSON data, line 1: ..._fragment_ratio": 1.0, "strand_mapping_bias": NaN...
```

**Comment by Miserlou** [comment]
We actually encountered this before, and is fixed in newer Salmon: https://github.com/COMBINE-lab/salmon/issues/279 

So, related: https://github.com/AlexsLemonade/refinebio/issues/1159
