### ISSUE TITLE
Investigate Compendia Failure

### ISSUE THREAD

**Issue by wvauclain** [AlexsLemonade/refinebio#1398]
### Context

I was trying to generate a new zebrafish compendium for @jaclyn-taroni after the code was changed to run the compendium on a processor instance.

### Problem or idea

I started the job on Friday, and it looks like it failed because the new compendium isn't on S3 or on the `/compendia/` endpoint.

### Solution or next step

Try running another compendium and tracing its output to find the error.

**Comment by arielsvn** [comment]
Seems like it's still running:

```
ubuntu@ip-10-0-205-197:~$ nomad status | grep COMPENDIA
CREATE_COMPENDIA                              batch/parameterized  80        running  2019-07-12T16:39:28Z
```

**Comment by wvauclain** [comment]
That's only the parameterized `CREATE_COMPENDIA` job. A dispatch job is created whenever you try to create a compendia, and this failed as far as I can tell.

**Comment by jaclyn-taroni** [comment]
Can we get this slotted for this sprint? I would like to send a zebrafish compendium to a collaborator as soon as possible.

**Comment by wvauclain** [comment]
It looks like the compendia job fails with this error:

```
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod Sentry is attempting to send 3 pending error messages
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod Waiting up to 10 seconds
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod Press Ctrl-C to quit
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod Using TensorFlow backend.
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod Traceback (most recent call last):
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod   File "manage.py", line 23, in <module>
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod Sentry is attempting to send 1 pending error messages
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod Waiting up to 10 seconds
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod     execute_from_command_line(sys.argv)
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod     utility.execute()
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 375, in execute
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod     self.fetch_command(subcommand).run_from_argv(self.argv)
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 224, in fetch_command
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod Press Ctrl-C to quit
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod     klass = load_command_class(app_name, subcommand)
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 36, in load_command_class
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod     module = import_module('%s.management.commands.%s' % (app_name, name))
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod   File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod     return _bootstrap._gcd_import(name[level:], package, level)
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod   File "/home/user/data_refinery_workers/processors/management/commands/create_compendia.py", line 19, in <module>
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod     from data_refinery_workers.processors import create_compendia
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod   File "/home/user/data_refinery_workers/processors/create_compendia.py", line 30, in <module>
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod     from data_refinery_workers.processors import utils, smasher, visualize
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod   File "/home/user/data_refinery_workers/processors/visualize.py", line 4, in <module>
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod     import datashader as ds
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/datashader/__init__.py", line 6, in <module>
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod     from .core import Canvas                                 # noqa (API import)
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/datashader/core.py", line 7, in <module>
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod     from xarray import DataArray, Dataset
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/xarray/__init__.py", line 26, in <module>
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod     from .coding.cftime_offsets import cftime_range
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/xarray/coding/cftime_offsets.py", line 46, in <module>
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod     from typing import ClassVar, Optional
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod ImportError: cannot import name 'ClassVar'
```

**Comment by kurtwheeler** [comment]
Looks like https://github.com/AlexsLemonade/refinebio/pull/1443 fixed this!
