### ISSUE TITLE
Quantpendias seem to be stuck

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio#1823]
### Context

Yesterday we ran quantpendia jobs for `HOMO_SAPIENS`, `MUS_MUSCULUS` and `DANIO_RERIO`

```
CREATE_QUANTPENDIA/dispatch-1571776183-d3109607   batch                80        running  2019-10-22T20:29:43Z
CREATE_QUANTPENDIA/dispatch-1571776420-889dce08   batch                80        running  2019-10-22T20:33:40Z
CREATE_QUANTPENDIA/dispatch-1571776659-8a07aa71   batch                80        running  2019-10-22T20:37:39Z
```

Only the one for `DANIO_RERIO` completed successfully [CREATE_QUANTPENDIA/dispatch-1571776183-d3109607](https://s3.amazonaws.com/data-refinery-s3-circleci-prod/v4uuojgiw7w8grng8tx7caiu_e762c998-3ecb-4a0e-a9cb-d55dc2fdf3b4_compendia.zip). The other two are still running after 20 hours.

### Problem or idea

The human and mouse jobs don't seem to be doing anything. I have been checking the number of downloaded quant files for both and they seem to be stuck.

```
$ find d4f84b68-9e55-495d-a913-9ece90d69939/output -maxdepth 2 -name "*_quant.sf" | wc -l
35789
$ find 8e3de724-7923-4b9a-bb77-4d0fdc64411b/output -maxdepth 2 -name "*_quant.sf" | wc -l
26976
```

It's likely in the part where we download the quant files in parallel https://github.com/AlexsLemonade/refinebio/blob/dev/workers/data_refinery_workers/processors/smashing_utils.py#L955

The sizes of the respective downloaded quant files:

```
$ du -hs d4f84b68-9e55-495d-a913-9ece90d69939
200G    d4f84b68-9e55-495d-a913-9ece90d69939
$ du -hs 8e3de724-7923-4b9a-bb77-4d0fdc64411b
213G    8e3de724-7923-4b9a-bb77-4d0fdc64411b
```

Also, looking and the instance's network usage. Looks that it hasn't downloaded anything in the last 10 hours.

![image](https://user-images.githubusercontent.com/1882507/67423964-3c339a80-f5a3-11e9-9c6f-95a11bc70b4f.png)

### Solution or next step

We need to investigate what might be causing this, some theories that we have had:

- Those two jobs are running on the smasher with the compendia which takes 3.5TB of RAM. Maybe they are competing for resources?

- Is it a problem to have too many threads writing to disk at the same time?

**Comment by arielsvn** [comment]
Also some logs of the running jobs

<details>

```
ubuntu@ip-10-0-242-7:~$ nomad status CREATE_QUANTPENDIA/dispatch-1571776420-889dce08
ID            = CREATE_QUANTPENDIA/dispatch-1571776420-889dce08
Name          = CREATE_QUANTPENDIA/dispatch-1571776420-889dce08
Submit Date   = 2019-10-22T20:33:40Z
Type          = batch
Priority      = 80
Datacenters   = dc1
Status        = running
Periodic      = false
Parameterized = false

Summary
Task Group  Queued  Starting  Running  Failed  Complete  Lost
jobs        0       0         1        0       0         0

Allocations
ID        Node ID   Task Group  Version  Desired  Status   Created    Modified
ec43716c  9bd000b8  jobs        0        run      running  22h8m ago  22h8m ago
ubuntu@ip-10-0-242-7:~$ nomad status ec43716c
ID                  = ec43716c
Eval ID             = dd0860a4
Name                = CREATE_QUANTPENDIA/dispatch-1571776420-889dce08.jobs[0]
Node ID             = 9bd000b8
Job ID              = CREATE_QUANTPENDIA/dispatch-1571776420-889dce08
Job Version         = 0
Client Status       = running
Client Description  = <none>
Desired Status      = run
Desired Description = <none>
Created             = 22h9m ago
Modified            = 22h9m ago

Task "create_quantpendia" is "running"
Task Resources
CPU         Memory           Disk    IOPS  Addresses
0/4000 MHz  7.4 GiB/8.0 GiB  10 MiB  0     

Task Events:
Started At     = 2019-10-22T20:33:42Z
Finished At    = N/A
Total Restarts = 0
Last Restart   = N/A

Recent Events:
Time                  Type        Description
2019-10-22T20:33:42Z  Started     Task started by client
2019-10-22T20:33:40Z  Driver      Downloading image ccdl/dr_compendia:latest
2019-10-22T20:33:40Z  Task Setup  Building Task Directory
2019-10-22T20:33:40Z  Received    Task received by client
ubuntu@ip-10-0-242-7:~$ nomad status CREATE_QUANTPENDIA/dispatch-1571776659-8a07aa71
ID            = CREATE_QUANTPENDIA/dispatch-1571776659-8a07aa71
Name          = CREATE_QUANTPENDIA/dispatch-1571776659-8a07aa71
Submit Date   = 2019-10-22T20:37:39Z
Type          = batch
Priority      = 80
Datacenters   = dc1
Status        = running
Periodic      = false
Parameterized = false

Summary
Task Group  Queued  Starting  Running  Failed  Complete  Lost
jobs        0       0         1        0       0         0

Allocations
ID        Node ID   Task Group  Version  Desired  Status   Created    Modified
5d8163c2  9bd000b8  jobs        0        run      running  22h5m ago  22h5m ago
ubuntu@ip-10-0-242-7:~$ nomad status 5d8163c2
ID                  = 5d8163c2
Eval ID             = 37409349
Name                = CREATE_QUANTPENDIA/dispatch-1571776659-8a07aa71.jobs[0]
Node ID             = 9bd000b8
Job ID              = CREATE_QUANTPENDIA/dispatch-1571776659-8a07aa71
Job Version         = 0
Client Status       = running
Client Description  = <none>
Desired Status      = run
Desired Description = <none>
Created             = 22h5m ago
Modified            = 22h5m ago

Task "create_quantpendia" is "running"
Task Resources
CPU          Memory           Disk    IOPS  Addresses
13/4000 MHz  7.4 GiB/8.0 GiB  10 MiB  0     

Task Events:
Started At     = 2019-10-22T20:37:40Z
Finished At    = N/A
Total Restarts = 0
Last Restart   = N/A

Recent Events:
Time                  Type        Description
2019-10-22T20:37:40Z  Started     Task started by client
2019-10-22T20:37:39Z  Driver      Downloading image ccdl/dr_compendia:latest
2019-10-22T20:37:39Z  Task Setup  Building Task Directory
2019-10-22T20:37:39Z  Received    Task received by client
```

</details>

**Comment by arielsvn** [comment]
Terminated one of the nomad jobs and got an error from one of the threads with 

`OSError: [Errno 12] Cannot allocate memory`

@kurtwheeler mentioned that we ran into this issue before, where the process hangs when it tries to create new threads but there's not enough memory for them. #1824 should increase the memory that we allocate for these jobs.

<details><summary>Logs</summary>

```
ubuntu@ip-10-0-242-7:~$ nomad stop CREATE_QUANTPENDIA/dispatch-1571776420-889dce08
==> Monitoring evaluation "6c0b1657"
    Evaluation triggered by job "CREATE_QUANTPENDIA/dispatch-1571776420-889dce08"
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "6c0b1657" finished with status "complete"
```

```
Exception in thread Thread-15664:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 366, in _handle_workers
    pool._maintain_pool()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 240, in _maintain_pool
    self._repopulate_pool()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 233, in _repopulate_pool
    w.start()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.5/multiprocessing/context.py", line 267, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 67, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```

```
Reading in : /home/user/data_store/GSE76862/GSM2039129_RM-1.CEL
Reading in : /home/user/data_store/GSM2353331/GSM2353331_A52084400939854091415421246947288.CEL
2019-10-23 19:47:33,047 i-0119de425230c426b [volume: -1] data_refinery_workers.processors.utils ERROR [processor_job: 29320865] [no_retry: False]: Unhandled exception caught while running processor function download_files in pipeline:
Traceback (most recent call last):
  File "/home/user/data_refinery_workers/processors/utils.py", line 383, in run_pipeline
    last_result = processor(last_result)
  File "/home/user/data_refinery_workers/processors/create_quantpendia.py", line 35, in download_files
    _make_dirs(job_context)
  File "/home/user/data_refinery_workers/processors/create_quantpendia.py", line 111, in _make_dirs
    os.makedirs(job_context["work_dir"])
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/user/data_store/smashed/8e3de724-7923-4b9a-bb77-4d0fdc64411b/'
```
```
2019-10-23 19:47:36,065 i-0119de425230c426b [volume: -1] data_refinery_workers.processors.utils ERROR [processor_job: 29320865] [pipeline_applied: CREATE_QUANTPENDIA] [failure_reason: Unhandled exception caught while running processor function download_files in pipeline: [Errno 17] File exists: '/home/user/data_store/smashed/8e3de724-7923-4b9a-bb77-4d0fdc64411b/'] [no_retry: False]: Processor job failed!
```

</details>

**Comment by arielsvn** [comment]
Also got this error when terminating the second quantpendia job:

```
ubuntu@ip-10-0-242-7:~$ nomad stop CREATE_QUANTPENDIA/dispatch-1571776659-8a07aa71
==> Monitoring evaluation "d68f3fe7"
    Evaluation triggered by job "CREATE_QUANTPENDIA/dispatch-1571776659-8a07aa71"
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "d68f3fe7" finished with status "complete"
```

```
2019-10-23 19:56:17,559 i-0119de425230c426b [volume: -1] data_refinery_workers.processors.utils ERROR [processor_job: 29320867] [no_retry: False]: Unhandled exception caught while running processor function download_files in pipeline:
Traceback (most recent call last):
  File "/home/user/data_refinery_workers/processors/utils.py", line 383, in run_pipeline
    last_result = processor(last_result)
  File "/home/user/data_refinery_workers/processors/create_quantpendia.py", line 35, in download_files
    _make_dirs(job_context)
  File "/home/user/data_refinery_workers/processors/create_quantpendia.py", line 111, in _make_dirs
    os.makedirs(job_context["work_dir"])
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/user/data_store/smashed/d4f84b68-9e55-495d-a913-9ece90d69939/'
2019-10-23 19:56:20,507 i-0119de425230c426b [volume: -1] data_refinery_workers.processors.utils ERROR [pipeline_applied: CREATE_QUANTPENDIA] [processor_job: 29320867] [failure_reason: Unhandled exception caught while running processor function download_files in pipeline: [Errno 17] File exists: '/home/user/data_store/smashed/d4f84b68-9e55-495d-a913-9ece90d69939/'] [no_retry: False]: Processor job failed!
```

**Comment by arielsvn** [comment]
Human and mouse jobs failed again, looks like they were OOM-killed:

```
data_refinery=> select * from processor_jobs where pipeline_applied='CREATE_QUANTPENDIA' order by created_at desc limit 10;
    id    |  pipeline_applied  | no_retry | ram_amount | volume_index |          start_time           |           end_time            | success |                  nomad_job_id                   | num_retries | retried |      worker_id      | worker_version  | failure_reason |          created_at           |         last_modified         | retried_job_id 
----------+--------------------+----------+------------+--------------+-------------------------------+-------------------------------+---------+-------------------------------------------------+-------------+---------+---------------------+-----------------+----------------+-------------------------------+-------------------------------+----------------
 29324093 | CREATE_QUANTPENDIA | f        |       2048 |              | 2019-10-30 21:30:12.336234+00 |                               | f       | CREATE_QUANTPENDIA/dispatch-1572470710-de4ace70 |           2 | t       | i-0c5a2f5e8ad26c53e | v1.28.15-hotfix |                | 2019-10-30 21:25:10.477218+00 | 2019-10-30 23:05:13.033214+00 |               
 29324092 | CREATE_QUANTPENDIA | f        |       2048 |              | 2019-10-30 21:39:12.58793+00  |                               | f       | CREATE_QUANTPENDIA/dispatch-1572470710-65d9c637 |           2 | t       | i-0c5a2f5e8ad26c53e | v1.28.15-hotfix |                | 2019-10-30 21:25:10.005835+00 | 2019-10-30 23:10:03.60274+00  |               
```

The latest logs we have for each one of them are:

**Job 29324093** [SRP170074](https://www.refine.bio/experiments/SRP170074/nrf2-activation-promotes-lung-cancer-metastasis-by-blocking-degradation-of-bach1) was the latest experiment that it tried to download

```
2019-10-30 23:04:59,651 i-0c5a2f5e8ad26c53e [volume: 0] data_refinery_workers.processors.create_quantpendia DEBUG [job_id: 29324093] [accession_code: SRP077449] [total_cpu: 93.7] [process_ram: 1.1086463928222656]: Downloading quant.sf files for quantpendia.
2019-10-30 23:05:00,586 i-0c5a2f5e8ad26c53e [volume: 0] data_refinery_workers.processors.create_quantpendia DEBUG [job_id: 29324093] [accession_code: GSE12538] [total_cpu: 90.1] [process_ram: 1.1086463928222656]: Downloading quant.sf files for quantpendia.
2019-10-30 23:05:01,352 i-0c5a2f5e8ad26c53e [volume: 0] data_refinery_workers.processors.create_quantpendia DEBUG [job_id: 29324093] [accession_code: SRP170074] [total_cpu: 90.6] [process_ram: 1.1086463928222656]: Downloading quant.sf files for quantpendia.
```

**Job 29324092** [GSE18736](https://www.refine.bio/experiments/GSE18736/differential-expression-of-nf-kb-target-genes-in-malt-lymphoma-with-and-without-chromosome-translocation-insights-into-molecular-mechanism) was the latest experiment that it tried to download

```
2019-10-30 23:00:49,911 i-0c5a2f5e8ad26c53e [volume: 0] data_refinery_workers.processors.create_quantpendia DEBUG [accession_code: SRP103855] [total_cpu: 95.6] [process_ram: 1.1149635314941406] [job_id: 29324092]: Downloading quant.sf files for quantpendia.
2019-10-30 23:00:51,015 i-0c5a2f5e8ad26c53e [volume: 0] data_refinery_workers.processors.create_quantpendia DEBUG [accession_code: GSE117178] [total_cpu: 95.3] [process_ram: 1.1149635314941406] [job_id: 29324092]: Downloading quant.sf files for quantpendia.
2019-10-30 23:00:51,973 i-0c5a2f5e8ad26c53e [volume: 0] data_refinery_workers.processors.create_quantpendia DEBUG [accession_code: GSE18736] [total_cpu: 96.1] [process_ram: 1.114990234375] [job_id: 29324092]: Downloading quant.sf files for quantpendia.
```

**Comment by arielsvn** [comment]
Looks like human and mouse failed again, also OOM_killed.

```
data_refinery=> select * from processor_jobs where pipeline_applied='CREATE_QUANTPENDIA' order by created_at desc limit 10;
    id    |  pipeline_applied  | no_retry | ram_amount | volume_index |          start_time           |           end_time            | success |                  nomad_job_id                   | num_retries | retried |      worker_id      | worker_version  | failure_reason |          created_at           |         last_modified         | retried_job_id 
----------+--------------------+----------+------------+--------------+-------------------------------+-------------------------------+---------+-------------------------------------------------+-------------+---------+---------------------+-----------------+----------------+-------------------------------+-------------------------------+----------------
 29356660 | CREATE_QUANTPENDIA | f        |       2048 |              | 2019-11-05 01:01:06.942926+00 |                               | f       | CREATE_QUANTPENDIA/dispatch-1572915619-24e44161 |           2 | t       | i-077e64d9bea609379 | v1.28.17-hotfix |                | 2019-11-05 01:00:18.913592+00 | 2019-11-05 02:35:06.573717+00 |               
 29356659 | CREATE_QUANTPENDIA | f        |       2048 |              | 2019-11-05 01:00:44.8023+00   |                               | f       | CREATE_QUANTPENDIA/dispatch-1572915604-ee7152c4 |           2 | t       | i-077e64d9bea609379 | v1.28.17-hotfix |                | 2019-11-05 01:00:03.860275+00 | 2019-11-05 02:35:06.570754+00 |               
```

In all cases, we finished downloaded all `quant.sf` files:

```
DEBUG [total_cpu: 23.6] [process_ram: 4.393108367919922] [job_id: 29356660] [total_downloaded_files: 118830]: Finished downloading quant.sf files for quantpendia.
```

But the jobs died afterward, with no additional logs.

**Comment by arielsvn** [comment]
Human quantpendia failed, the last log we got from it was:

```
DEBUG [total_cpu: 5.0] [organism_name: HOMO_SAPIENS] [process_ram: 2.128643035888672] [job_id: 29383175]: Finished metadata for quantpendia. Generating archive.
```

It seems like the archive was successfully generated. I'm going to investigate why we didn't create the computed file.

```
ubuntu@ip-10-0-32-135:/var/ebs/smashed/e48ed885-8825-4c77-8d2f-31761ac69996$ ls -lah
total 8.1G
drwxr-xr-x    3 ubuntu ubuntu 4.0K Nov 12 04:18 .
drwxr-xr-x    3 ubuntu ubuntu 4.0K Nov 11 22:24 ..
-rw-r--r--    1 ubuntu ubuntu 8.1G Nov 12 04:50 HOMO_SAPIENS_rnaseq_compendia.zip
drwxr-xr-x 6318 ubuntu ubuntu 192K Nov 12 04:18 output
```

The jobs look as if they were OOM-Killed:

```
data_refinery=> select * from processor_jobs where pipeline_applied='CREATE_QUANTPENDIA' order by created_at desc limit 3;
    id    |  pipeline_applied  | no_retry | ram_amount | volume_index |          start_time           | end_time | success |                  nomad_job_id                   | num_retries | retried |      worker_id      | worker_version  | failure_reason |          created_at           |         last_modified         | retried_job_id 
----------+--------------------+----------+------------+--------------+-------------------------------+----------+---------+-------------------------------------------------+-------------+---------+---------------------+-----------------+----------------+-------------------------------+-------------------------------+----------------
 29383175 | CREATE_QUANTPENDIA | f        |       2048 |              | 2019-11-12 03:18:10.967651+00 |          | f       | CREATE_QUANTPENDIA/dispatch-1573522203-c6d08e55 |           2 | t       | i-019fca3fba3212052 | v1.28.20-hotfix |                | 2019-11-12 01:30:03.019211+00 | 2019-11-12 03:18:10.96768+00  |               
 29381570 | CREATE_QUANTPENDIA | f        |       2048 |              | 2019-11-11 23:55:42.827996+00 |          | f       | CREATE_QUANTPENDIA/dispatch-1573516505-bca62f48 |           1 | t       | i-019fca3fba3212052 | v1.28.20-hotfix |                | 2019-11-11 23:55:05.393779+00 | 2019-11-12 01:30:03.126316+00 |       29383175
 29380081 | CREATE_QUANTPENDIA | f        |       2048 |              | 2019-11-11 22:24:16.312182+00 |          | f       | CREATE_QUANTPENDIA/dispatch-1573510725-f8c7b14a |           0 | t       | i-019fca3fba3212052 | v1.28.20-hotfix |                | 2019-11-11 22:18:44.882597+00 | 2019-11-11 23:55:05.535677+00 |       29381570
(3 rows)
```

**Comment by arielsvn** [comment]
We now have a human quantpendia, and mouse is being processed. This worked after doubling the ram and running the jobs on the smasher instance.
