### ISSUE TITLE
Quantpendia failed to upload to S3

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#1836]
### Context

We kicked off quantpendia jobs for all organisms but they weren't succeeding because they couldn't upload to S3.

### Problem or idea

This is probably just because the worker instances don't have access to the compendia S3 bucket. The smasher probably has those permissions, but it looks like the workers don't.

### Solution or next step

Give worker instances permissions to push to the compendia S3 bucket.

**Comment by kurtwheeler** [comment]
Looks like my gut was wrong about this, it's not because of S3 permissions, it looks like we're deleting the file before we upload it:
```
2019-10-25 21:45:58,588 i-00ff13b277ae5d3b2 [volume: 0] data_refinery_common.models.models ERROR [s3_bucket: data-refinery-s3-circleci-prod] [s3_key: vntntd5ajb0l05c2wwn51rnu_BOS_TAURUS_rnas
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/data_refinery_common/models/models.py", line 992, in sync_to_s3
    'StorageClass': 'STANDARD_IA'
  File "/usr/local/lib/python3.5/dist-packages/boto3/s3/inject.py", line 131, in upload_file
    extra_args=ExtraArgs, callback=Callback)
  File "/usr/local/lib/python3.5/dist-packages/boto3/s3/transfer.py", line 279, in upload_file
    future.result()
  File "/usr/local/lib/python3.5/dist-packages/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/usr/local/lib/python3.5/dist-packages/s3transfer/futures.py", line 265, in result
    raise self._exception
  File "/usr/local/lib/python3.5/dist-packages/s3transfer/tasks.py", line 255, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/s3transfer/upload.py", line 549, in _submit
    upload_input_manager.provide_transfer_size(transfer_future)
  File "/usr/local/lib/python3.5/dist-packages/s3transfer/upload.py", line 237, in provide_transfer_size
    transfer_future.meta.call_args.fileobj))
  File "/usr/local/lib/python3.5/dist-packages/s3transfer/utils.py", line 243, in get_file_size
    return os.path.getsize(filename)
  File "/usr/lib/python3.5/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/data_store/smashed/a2213fa8-5616-4062-826f-b2e8af0f8ed9/BOS_TAURUS_rnaseq_compendia.zip'
```

**Comment by arielsvn** [comment]
Not sure why that's happening, I'm gonna look into it.
