### ISSUE TITLE
Run fungi and bacteria for supported strains

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#2087]
### Context

#1722 #2035  enabled us to process RNASeq samples from specific species/strains of bacteria and fungi. We haven't run any of them in production yet though.

### Problem or idea

We should run the organisms that we have strains selected for by expert opinions, which is every row of https://github.com/AlexsLemonade/refinebio/blob/dev/config/organism_strain_mapping.csv

### Solution or next step

Kick off surveyor jobs for the Fungi and Bacteria strains. Let them get processed. Look at the successes/failures and determine if there are additional issues that need to be filed or if we hit about the success rate we would expect given that there's some bad data out there in the world.

**Comment by arielsvn** [comment]
I'm about to run the surveyor for those organisms. Looks like we have some samples processed for some of them:

```
organism PSEUDOMONAS_AERUGINOSA has 1127 samples (992 processed)
organism CANDIDA_ALBICANS has 354 samples (0 processed)
organism ESCHERICHIA_COLI has 1143 samples (1009 processed)
```

<summary>

```py
for name in ["PSEUDOMONAS_AERUGINOSA", "CANDIDA_ALBICANS", "ESCHERICHIA_COLI"]:
    samples = Organism.objects.get(name=name).sample_set.all()
    print(
        "organism {0} has {1} samples ({2} processed)".format(
            name, samples.count(), samples.filter(is_processed=True).count()
        )
    )
```

</summary>

**Comment by arielsvn** [comment]
I ran the following command

```
nomad job dispatch -meta FILE=https://data-refinery-test-assets.s3.amazonaws.com/survey-ensembl.txt SURVEYOR_DISPATCHER
```

And `survey-ensembl.txt` content is:

```
PSEUDOMONAS_AERUGINOSA, EnsemblBacteria
CANDIDA_ALBICANS, EnsemblFungi
ESCHERICHIA_COLI, EnsemblBacteria
```

**Comment by arielsvn** [comment]
That failed :/ Looks like there's something strange happening with the organism names, saw these errors on the logs:

```
Unable to retrieve NCBI taxonomy ID number for organism with name: ESCHERICHIA_COLI_GCA_001012635

ERROR: Unable to retrieve NCBI taxonomy ID number for organism with name: CANDIDA_ALBICANS_SC5314_GCA_000784635
```

<details><summary>all logs</summary>

```
2020-01-22 17:02:45,973 i-0327b7e8f917d870c [volume: 0] data_refinery_common.models.organism ERROR: Unable to retrieve NCBI taxonomy ID number for organism with name: CANDIDA_ALBICANS_SC5314_GCA_000784635
2020-01-22 17:02:46,194 i-0327b7e8f917d870c [volume: 0] data_refinery_workers.processors.utils ERROR [no_retry: False] [processor_job: 29555832]: Unhandled exception caught while running processor function _populate_index_object in pipeline:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/data_refinery_common/models/organism.py", line 179, in get_object_for_name
    organism = cls.objects.filter(name=name)[0]
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 309, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.IntegrityError: duplicate key value violates unique constraint "organisms_taxonomy_id_key"
DETAIL:  Key (taxonomy_id)=(0) already exists.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/user/data_refinery_workers/processors/utils.py", line 406, in run_pipeline
    last_result = processor(last_result)
  File "/home/user/data_refinery_workers/processors/transcriptome_index.py", line 367, in _populate_index_object
    organism_object = Organism.get_object_for_name(job_context["organism_name"])
  File "/usr/local/lib/python3.5/dist-packages/data_refinery_common/models/organism.py", line 191, in get_object_for_name
    organism.save()
  File "/usr/local/lib/python3.5/dist-packages/data_refinery_common/models/organism.py", line 136, in save
    return super(Organism, self).save(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/sql/compiler.py", line 1368, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/dist-packages/raven/contrib/django/client.py", line 127, in execute
    return real_execute(self, sql, params)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/dist-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "organisms_taxonomy_id_key"
DETAIL:  Key (taxonomy_id)=(0) already exists.

2020-01-22 17:02:46,328 i-0327b7e8f917d870c [volume: 0] data_refinery_workers.processors.utils ERROR [processor_job: 29555832] [pipeline_applied: TRANSCRIPTOME_INDEX_SHORT] [no_retry: False] [failure_reason: Unhandled exception caught while running processor function _populate_index_object in pipeline: duplicate key value violates unique constraint "organisms_taxonomy_id_key"
DETAIL:  Key (taxonomy_id)=(0) already exists.



2020-01-22 17:05:10,201 i-0327b7e8f917d870c [volume: 0] data_refinery_common.models.organism ERROR: Unable to retrieve NCBI taxonomy ID number for organism with name: ESCHERICHIA_COLI_GCA_001012635
2020-01-22 17:05:10,476 i-0327b7e8f917d870c [volume: 0] data_refinery_workers.processors.utils ERROR [no_retry: False] [processor_job: 29555848]: Unhandled exception caught while running processor function _populate_index_object in pipeline:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/data_refinery_common/models/organism.py", line 179, in get_object_for_name
    organism = cls.objects.filter(name=name)[0]
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 309, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.IntegrityError: duplicate key value violates unique constraint "organisms_taxonomy_id_key"
DETAIL:  Key (taxonomy_id)=(0) already exists.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/user/data_refinery_workers/processors/utils.py", line 406, in run_pipeline
    last_result = processor(last_result)
  File "/home/user/data_refinery_workers/processors/transcriptome_index.py", line 367, in _populate_index_object
    organism_object = Organism.get_object_for_name(job_context["organism_name"])
  File "/usr/local/lib/python3.5/dist-packages/data_refinery_common/models/organism.py", line 191, in get_object_for_name
    organism.save()
  File "/usr/local/lib/python3.5/dist-packages/data_refinery_common/models/organism.py", line 136, in save
    return super(Organism, self).save(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/sql/compiler.py", line 1368, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/dist-packages/raven/contrib/django/client.py", line 127, in execute
    return real_execute(self, sql, params)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/dist-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "organisms_taxonomy_id_key"
DETAIL:  Key (taxonomy_id)=(0) already exists.
2020-01-22 17:05:10,579 i-0327b7e8f917d870c [volume: 0] data_refinery_workers.processors.utils ERROR [failure_reason: Unhandled exception caught while running processor function _populate_index_object in pipeline: duplicate key value violates unique constraint "organisms_taxonomy_id_key"
DETAIL:  Key (taxonomy_id)=(0) already exists.
] [no_retry: False] [pipeline_applied: TRANSCRIPTOME_INDEX_SHORT] [processor_job: 29555848]: Processor job failed!
Sentry responded with an API error: RateLimited(None)
['Unable to retrieve NCBI taxonomy ID number for organism with name: ESCHERICHIA_COLI_GCA_001012635']
Sentry responded with an API error: RateLimited(None)
['Processor job failed!']
```

</summary>

**Comment by kurtwheeler** [comment]
That's super weird because I tested those organisms.... I wonder if the API changed or if I changed something for a unit test and forgot to rerun the functional test? I'll dig into this, it's an error in code that I recently wrote.

**Comment by kurtwheeler** [comment]
Ok, looks like this ran successfully for a high percentage of samples that weren't affected by this issue: https://github.com/AlexsLemonade/refinebio/issues/2123.

The rest of these will have to be addressed after that is taken care of.
