### ISSUE TITLE
Surveying GSE56080 throws an exception somewhere in `GEOparse`'s code

### ISSUE THREAD

**Issue by wvauclain** [AlexsLemonade/refinebio#2797]
### Context

I ran into this yesterday while trying to find reference data for the illumina tests.

### Problem or idea

An exception gets thrown when surveying GSE56080:
```
OSError: Download failed due to 'Downloaded size do not match the expected size for http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?targ=self&acc=GPL6885&form=text&view=brief'. ID could be incorrect or the data might not be public yet.
```

<details>
<summary>Full backtrace</summary>

```
$ ./foreman/run_surveyor.sh survey_all --accession GSE56080
...
2021-06-23 21:04:18,627 local [volume: 0] data_refinery_foreman.surveyor.external_source ERROR [survey_job: 7]: Exception caught while discovering samples. Terminating survey job.
Traceback (most recent call last):
  File "/home/user/data_refinery_foreman/surveyor/geo.py", line 281, in create_experiment_and_samples_from_api
    sample_object = Sample.objects.get(accession_code=sample_accession_code)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 437, in get
    self.model._meta.object_name
data_refinery_common.models.sample.Sample.DoesNotExist: Sample matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/GEOparse/utils.py", line 80, in download_from_url
    fn.download(silent=silent, force=force)
  File "/usr/local/lib/python3.6/dist-packages/GEOparse/downloader.py", line 82, in download
    _download()
  File "/usr/local/lib/python3.6/dist-packages/GEOparse/downloader.py", line 51, in _download
    self._download_http(silent=silent)
  File "/usr/local/lib/python3.6/dist-packages/GEOparse/downloader.py", line 227, in _download_http
    "Downloaded size do not match the expected size for %s" % (self.url)
ValueError: Downloaded size do not match the expected size for http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?targ=self&acc=GPL6885&form=text&view=brief

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/data_refinery_foreman/surveyor/external_source.py", line 168, in survey
    experiment, samples = self.discover_experiment_and_samples()
  File "/home/user/data_refinery_foreman/surveyor/geo.py", line 500, in discover_experiment_and_samples
    experiment, samples = self.create_experiment_and_samples_from_api(experiment_accession_code)
  File "/home/user/data_refinery_foreman/surveyor/geo.py", line 316, in create_experiment_and_samples_from_api
    self.set_platform_properties(sample_object, sample.metadata, gse)
  File "/home/user/data_refinery_foreman/surveyor/geo.py", line 78, in set_platform_properties
    external_accession, destdir=self.get_temp_path(), how="brief", silent=True
  File "/usr/local/lib/python3.6/dist-packages/GEOparse/GEOparse.py", line 94, in get_GEO
    aspera=aspera,
  File "/usr/local/lib/python3.6/dist-packages/GEOparse/GEOparse.py", line 237, in get_GEO_file
    utils.download_from_url(url, filepath, silent=silent, aspera=aspera)
  File "/usr/local/lib/python3.6/dist-packages/GEOparse/utils.py", line 84, in download_from_url
    + "data might not be public yet."
OSError: Download failed due to 'Downloaded size do not match the expected size for http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?targ=self&acc=GPL6885&form=text&view=brief'. ID could be incorrect or the data might not be public yet.
```
</details>

### Solution or next step

Figure out if this is a problem with our code or with `GEOparse`

**Comment by wvauclain** [comment]
I just tried again and it surveyed successfully
