### ISSUE TITLE
QN reference generation is broken

### ISSUE THREAD

**Issue by wvauclain** [AlexsLemonade/refinebio#2887]
### Context

Trying to test my last cron job test.

### Problem or idea

```
2021-08-09 21:10:36,468 i-0c7b928a370a5cc81 data_refinery_common.message_queue WARNING [job_name: QN_REFERENCE] [reason: An error occurred (ClientException) when calling the SubmitJob operation: JobDefinition name will_dev_QN_REFERENCE does not exist or is not in ACTIVE status] [job_id: 5757]: Unable to Dispatch Batch Job.
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/user/data_refinery_foreman/surveyor/management/commands/dispatch_qn_jobs.py", line 107, in handle
    dispatch_qn_job_if_eligible(organism)
  File "/home/user/data_refinery_foreman/surveyor/management/commands/dispatch_qn_jobs.py", line 87, in dispatch_qn_job_if_eligible
    send_job(ProcessorPipeline.QN_REFERENCE, job)
  File "/usr/local/lib/python3.6/dist-packages/data_refinery_common/message_queue.py", line 322, in send_job
    parameters={"job_name": job_type.value, "job_id": str(job.id)},
  File "/usr/local/lib/python3.6/dist-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ClientException: An error occurred (ClientException) when calling the SubmitJob operation: JobDefinition name will_dev_QN_REFERENCE does not exist or is not in ACTIVE status
```

### Solution or next step

Make the dispatcher handle RAM tiering for QN reference jobs.

**Comment by kurtwheeler** [comment]
This was fixed in https://github.com/AlexsLemonade/refinebio/pull/2908
