### ISSUE TITLE
Fix failing test_foreman job

### ISSUE THREAD

**Issue by arkid15r** [AlexsLemonade/refinebio#3080]
### Context

The error message(s):
https://github.com/AlexsLemonade/refinebio/actions/runs/3109588470/jobs/5039931138#step:12:3093

```
======================================================================
ERROR: test_survey (data_refinery_foreman.surveyor.test_sra.SraSurveyorTestCase)
A Simple test of the SRA surveyor.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/data_refinery_foreman/surveyor/test_sra.py", line 57, in test_survey
    sra_surveyor.discover_experiment_and_samples()
  File "/home/user/data_refinery_foreman/surveyor/sra.py", line 681, in discover_experiment_and_samples
    return self._generate_experiment_and_samples(accession)
  File "/home/user/data_refinery_foreman/surveyor/sra.py", line 446, in _generate_experiment_and_samples
    files_urls = [SraSurveyor._build_ncbi_file_url(run_accession)]
  File "/home/user/data_refinery_foreman/surveyor/sra.py", line 346, in _build_ncbi_file_url
    download_url = get_fasp_sra_download(run_accession)
  File "/usr/local/lib/python3.6/dist-packages/data_refinery_common/utils.py", line 335, in get_fasp_sra_download
    sra_url = full_url.split("fasp://")[1]
IndexError: list index out of range
```

https://github.com/AlexsLemonade/refinebio/actions/runs/3109588470/jobs/5039931138#step:12:3217
```
Traceback (most recent call last):
  File "/usr/local/bin/coverage", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/coverage/cmdline.py", line 871, in main
    status = CoverageScript().command_line(argv)
  File "/usr/local/lib/python3.6/dist-packages/coverage/cmdline.py", line 639, in command_line
    **report_args
  File "/usr/local/lib/python3.6/dist-packages/coverage/control.py", line 994, in xml_report
    return render_report(self.config.xml_output, XmlReporter(self), morfs)
  File "/usr/local/lib/python3.6/dist-packages/coverage/report.py", line 32, in render_report
    outfile = open(output_path, "w", **open_kwargs)
PermissionError: [Errno 13] Permission denied: 'data_store/coverage.xml'
Error: Process completed with exit code 1.
```

### Solution or next step
Fix the tests.

**Comment by arkid15r** [comment]
Fixed by https://github.com/AlexsLemonade/refinebio/pull/3254 and https://github.com/AlexsLemonade/refinebio/pull/3270
