### ISSUE TITLE
Fix test_common markupsafe issue

### ISSUE THREAD

**Issue by arkid15r** [AlexsLemonade/refinebio#3201]
### Context

On the way to a healthy CI/CD environment all failing tests need to be fixed.

### Problem or idea
```

#13 27.11 Collecting MarkupSafe>=2.0 (from jinja2->rpy2==3.4.5)
#13 27.25   Downloading https://files.pythonhosted.org/packages/95/7e/68018b70268fb4a2a605e2be44ab7b4dd7ce7808adae6c5ef32e34f4b55a/MarkupSafe-2.1.2.tar.gz
#13 27.44     Complete output from command python setup.py egg_info:
#13 27.44     Traceback (most recent call last):
#13 27.44       File "<string>", line 1, in <module>
#13 27.44       File "/tmp/pip-build-zu8nq2tv/MarkupSafe/setup.py", line 65, in <module>
#13 27.44         run_setup(True)
#13 27.44       File "/tmp/pip-build-zu8nq2tv/MarkupSafe/setup.py", line 41, in run_setup
#13 27.44         setup(
#13 27.44       File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
#13 27.44         return distutils.core.setup(**attrs)
#13 27.44       File "/usr/lib/python3.8/distutils/core.py", line 121, in setup
#13 27.44         dist.parse_config_files()
#13 27.44       File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 493, in parse_config_files
#13 27.44         parse_configuration(self, self.command_options,
#13 27.44       File "/usr/lib/python3/dist-packages/setuptools/config.py", line 106, in parse_configuration
#13 27.44         meta.parse()
#13 27.44       File "/usr/lib/python3/dist-packages/setuptools/config.py", line 382, in parse
#13 27.44         section_parser_method(section_options)
#13 27.44       File "/usr/lib/python3/dist-packages/setuptools/config.py", line 355, in parse_section
#13 27.44         self[name] = value
#13 27.44       File "/usr/lib/python3/dist-packages/setuptools/config.py", line 173, in __setitem__
#13 27.44         value = parser(value)
#13 27.44       File "/usr/lib/python3/dist-packages/setuptools/config.py", line 430, in _parse_version
#13 27.44         version = self._parse_attr(value)
#13 27.44       File "/usr/lib/python3/dist-packages/setuptools/config.py", line 305, in _parse_attr
#13 27.44         module = import_module(module_name)
#13 27.44       File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
#13 27.44         return _bootstrap._gcd_import(name[level:], package, level)
#13 27.44       File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
#13 27.44       File "<frozen importlib._bootstrap>", line 991, in _find_and_load
#13 27.44       File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
#13 27.44     ModuleNotFoundError: No module named 'markupsafe'
#13 27.44     
#13 27.44     ----------------------------------------
#13 27.47 Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-zu8nq2tv/MarkupSafe/
#13 ERROR: executor failed running [/bin/bash -o pipefail -c pip3 install --ignore-installed --no-cache-dir -r requirements.txt &&     pip3 install --ignore-installed --no-cache-dir rpy2==3.4.5]: exit code: 1
```

### Solution or next step

Resolve the dependency issue.

**Comment by arkid15r** [comment]
Resolved in https://github.com/AlexsLemonade/refinebio/pull/3227
