### ISSUE TITLE
Fix no_op NameError: name 'testing_utils' is not defined

### ISSUE THREAD

**Issue by arkid15r** [AlexsLemonade/refinebio#3206]
### Context

In order to restore staging/prod deploy process CI/CD tests need to be fixed.

### Problem or idea

```
System check identified no issues (0 silenced).
E
======================================================================
ERROR: test_illumina_imports (tests.processors.test_imports.ImportTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/tests/processors/test_imports.py", line 28, in test_illumina_imports
    import tests.processors.test_illumina
  File "/home/user/tests/processors/test_illumina.py", line 154, in <module>
    class IlluminaToPCLTestCase(TestCase, testing_utils.ProcessorJobTestCaseMixin):
NameError: name 'testing_utils' is not defined
```

### Solution or next step

Resolve NameError exception problem (use right module path).

**Comment by arkid15r** [comment]
Resolved in https://github.com/AlexsLemonade/refinebio/pull/3136
