### ISSUE TITLE
Fix test_illumina No such file or directory: 'file' error

### ISSUE THREAD

**Issue by arkid15r** [AlexsLemonade/refinebio#3211]
### Context

In order to restore staging/prod deploy process CI/CD tests need to be fixed.

### Problem or idea

```
Traceback (most recent call last):
  File "/home/user/data_refinery_workers/processors/utils.py", line 405, in run_pipeline
    last_result = processor(last_result)
  File "/home/user/data_refinery_workers/processors/illumina.py", line 75, in _detect_encoding
    encoding = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'file'
2023-02-15 23:09:46,834 local data_refinery_workers.processors.utils ERROR [processor_job: 1] [pipeline_applied: ILLUMINA_TO_PCL] [failure_reason: Unhandled exception caught while running processor function _detect_encoding in pipeline: [Errno 2] No such file or directory: 'file'] [no_retry: False]: Processor job failed!
E2023-02-15 23:09:46,891 local data_refinery_workers.processors.utils DEBUG [processor_job: 2] [pipeline: ILLUMINA_TO_PCL]: Starting processor Job.
2023-02-15 23:09:46,921 local data_refinery_workers.processors.utils ERROR [processor_job: 2] [no_retry: False]: Unhandled exception caught while running processor function _detect_encoding in pipeline: 
Traceback (most recent call last):
  File "/home/user/data_refinery_workers/processors/utils.py", line 405, in run_pipeline
    last_result = processor(last_result)
  File "/home/user/data_refinery_workers/processors/illumina.py", line 75, in _detect_encoding
    encoding = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'file'
2023-02-15 23:09:46,924 local data_refinery_workers.processors.utils ERROR [processor_job: 2] [pipeline_applied: ILLUMINA_TO_PCL] [failure_reason: Unhandled exception caught while running processor function _detect_encoding in pipeline: [Errno 2] No such file or directory: 'file'] [no_retry: False]: Processor job failed!
F2023-02-15 23:09:46,960 local data_refinery_workers.processors.utils DEBUG [processor_job: 3] [pipeline: ILLUMINA_TO_PCL]: Starting processor Job.
2023-02-15 23:09:46,974 local data_refinery_workers.processors.utils ERROR [processor_job: 3] [no_retry: False]: Unhandled exception caught while running processor function _detect_encoding in pipeline: 
Traceback (most recent call last):
  File "/home/user/data_refinery_workers/processors/utils.py", line 405, in run_pipeline
    last_result = processor(last_result)
  File "/home/user/data_refinery_workers/processors/illumina.py", line 75, in _detect_encoding
    encoding = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'file'
2023-02-15 23:09:46,976 local data_refinery_workers.processors.utils ERROR [processor_job: 3] [pipeline_applied: ILLUMINA_TO_PCL] [failure_reason: Unhandled exception caught while running processor function _detect_encoding in pipeline: [Errno 2] No such file or directory: 'file'] [no_retry: False]: Processor job failed!
F2023-02-15 23:09:47,001 local data_refinery_workers.processors.utils DEBUG [processor_job: 4] [pipeline: ILLUMINA_TO_PCL]: Starting processor Job.
2023-02-15 23:09:47,014 local data_refinery_workers.processors.utils ERROR [processor_job: 4] [no_retry: False]: Unhandled exception caught while running processor function _detect_encoding in pipeline: 
Traceback (most recent call last):
  File "/home/user/data_refinery_workers/processors/utils.py", line 405, in run_pipeline
    last_result = processor(last_result)
  File "/home/user/data_refinery_workers/processors/illumina.py", line 75, in _detect_encoding
    encoding = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'file'
2023-02-15 23:09:47,017 local data_refinery_workers.processors.utils ERROR [processor_job: 4] [pipeline_applied: ILLUMINA_TO_PCL] [failure_reason: Unhandled exception caught while running processor function _detect_encoding in pipeline: [Errno 2] No such file or directory: 'file'] [no_retry: False]: Processor job failed!
F2023-02-15 23:09:47,049 local data_refinery_workers.processors.utils DEBUG [processor_job: 5] [pipeline: ILLUMINA_TO_PCL]: Starting processor Job.
2023-02-15 23:09:47,073 local data_refinery_workers.processors.utils ERROR [processor_job: 5] [no_retry: False]: Unhandled exception caught while running processor function _detect_encoding in pipeline: 
Traceback (most recent call last):
  File "/home/user/data_refinery_workers/processors/utils.py", line 405, in run_pipeline
    last_result = processor(last_result)
  File "/home/user/data_refinery_workers/processors/illumina.py", line 75, in _detect_encoding
    encoding = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'file'
2023-02-15 23:09:47,075 local data_refinery_workers.processors.utils ERROR [processor_job: 5] [pipeline_applied: ILLUMINA_TO_PCL] [failure_reason: Unhandled exception caught while running processor function _detect_encoding in pipeline: [Errno 2] No such file or directory: 'file'] [no_retry: False]: Processor job failed!
F2023-02-15 23:09:47,104 local data_refinery_workers.processors.utils DEBUG [processor_job: 6] [pipeline: ILLUMINA_TO_PCL]: Starting processor Job.
2023-02-15 23:09:47,120 local data_refinery_workers.processors.utils ERROR [processor_job: 6] [no_retry: False]: Unhandled exception caught while running processor function _detect_encoding in pipeline: 
Traceback (most recent call last):
  File "/home/user/data_refinery_workers/processors/utils.py", line 405, in run_pipeline
    last_result = processor(last_result)
  File "/home/user/data_refinery_workers/processors/illumina.py", line 75, in _detect_encoding
    encoding = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'file'
2023-02-15 23:09:47,123 local data_refinery_workers.processors.utils ERROR [processor_job: 6] [pipeline_applied: ILLUMINA_TO_PCL] [failure_reason: Unhandled exception caught while running processor function _detect_encoding in pipeline: [Errno 2] No such file or directory: 'file'] [no_retry: False]: Processor job failed!
F2023-02-15 23:09:47,147 local data_refinery_workers.processors.utils DEBUG [processor_job: 7] [pipeline: ILLUMINA_TO_PCL]: Starting processor Job.
2023-02-15 23:09:47,164 local data_refinery_workers.processors.utils ERROR [processor_job: 7] [no_retry: False]: Unhandled exception caught while running processor function _detect_encoding in pipeline: 
Traceback (most recent call last):
  File "/home/user/data_refinery_workers/processors/utils.py", line 405, in run_pipeline
    last_result = processor(last_result)
  File "/home/user/data_refinery_workers/processors/illumina.py", line 75, in _detect_encoding
    encoding = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'file'
2023-02-15 23:09:47,167 local data_refinery_workers.processors.utils ERROR [processor_job: 7] [pipeline_applied: ILLUMINA_TO_PCL] [failure_reason: Unhandled exception caught while running processor function _detect_encoding in pipeline: [Errno 2] No such file or directory: 'file'] [no_retry: False]: Processor job failed!
F2023-02-15 23:09:47,192 local data_refinery_workers.processors.utils DEBUG [processor_job: 8] [pipeline: ILLUMINA_TO_PCL]: Starting processor Job.
2023-02-15 23:09:47,205 local data_refinery_workers.processors.utils ERROR [processor_job: 8] [no_retry: False]: Unhandled exception caught while running processor function _detect_encoding in pipeline: 
Traceback (most recent call last):
  File "/home/user/data_refinery_workers/processors/utils.py", line 405, in run_pipeline
    last_result = processor(last_result)
  File "/home/user/data_refinery_workers/processors/illumina.py", line 75, in _detect_encoding
    encoding = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'file'
2023-02-15 23:09:47,208 local data_refinery_workers.processors.utils ERROR [processor_job: 8] [pipeline_applied: ILLUMINA_TO_PCL] [failure_reason: Unhandled exception caught while running processor function _detect_encoding in pipeline: [Errno 2] No such file or directory: 'file'] [no_retry: False]: Processor job failed!
F2023-02-15 23:09:47,239 local data_refinery_workers.processors.utils DEBUG [processor_job: 9] [pipeline: ILLUMINA_TO_PCL]: Starting processor Job.
2023-02-15 23:09:47,258 local data_refinery_workers.processors.utils ERROR [processor_job: 9] [no_retry: False]: Unhandled exception caught while running processor function _detect_encoding in pipeline: 
Traceback (most recent call last):
  File "/home/user/data_refinery_workers/processors/utils.py", line 405, in run_pipeline
    last_result = processor(last_result)
  File "/home/user/data_refinery_workers/processors/illumina.py", line 75, in _detect_encoding
    encoding = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'file'
2023-02-15 23:09:47,261 local data_refinery_workers.processors.utils ERROR [processor_job: 9] [pipeline_applied: ILLUMINA_TO_PCL] [failure_reason: Unhandled exception caught while running processor function _detect_encoding in pipeline: [Errno 2] No such file or directory: 'file'] [no_retry: False]: Processor job failed!
F2023-02-15 23:09:47,311 local data_refinery_workers.processors.utils DEBUG [processor_job: 10] [pipeline: ILLUMINA_TO_PCL]: Starting processor Job.
2023-02-15 23:09:47,339 local data_refinery_workers.processors.utils ERROR [processor_job: 10] [no_retry: False]: Unhandled exception caught while running processor function _detect_encoding in pipeline: 
Traceback (most recent call last):
  File "/home/user/data_refinery_workers/processors/utils.py", line 405, in run_pipeline
    last_result = processor(last_result)
  File "/home/user/data_refinery_workers/processors/illumina.py", line 75, in _detect_encoding
    encoding = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'file'
2023-02-15 23:09:47,342 local data_refinery_workers.processors.utils ERROR [processor_job: 10] [pipeline_applied: ILLUMINA_TO_PCL] [failure_reason: Unhandled exception caught while running processor function _detect_encoding in pipeline: [Errno 2] No such file or directory: 'file'] [no_retry: False]: Processor job failed!
FEEE.
======================================================================
ERROR: test_bad_illumina_detection (tests.processors.test_illumina.IlluminaToPCLTestCase)
With the wrong species, this will fail the platform detection threshold.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/tests/processors/test_illumina.py", line 191, in test_bad_illumina_detection
    self.assertTrue(final_context["abort"])
KeyError: 'abort'

======================================================================
ERROR: test_sanitize_file_GSM_footer (tests.processors.test_illumina.IlluminaToPCLTestCase)
Some samples have this weird footer that we want to filter out
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/tests/processors/test_illumina.py", line 500, in test_sanitize_file_GSM_footer
    results = _try_sanitizing_file(contents)
  File "/home/user/tests/processors/test_illumina.py", line 100, in _try_sanitizing_file
    job_context = illumina._detect_encoding(job_context)
  File "/home/user/data_refinery_workers/processors/illumina.py", line 75, in _detect_encoding
    encoding = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'file'

======================================================================
ERROR: test_sanitize_file_hash_header (tests.processors.test_illumina.IlluminaToPCLTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/tests/processors/test_illumina.py", line 481, in test_sanitize_file_hash_header
    results = _try_sanitizing_file(contents)
  File "/home/user/tests/processors/test_illumina.py", line 100, in _try_sanitizing_file
    job_context = illumina._detect_encoding(job_context)
  File "/home/user/data_refinery_workers/processors/illumina.py", line 75, in _detect_encoding
    encoding = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'file'

======================================================================
ERROR: test_sanitize_file_soft_example (tests.processors.test_illumina.IlluminaToPCLTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/tests/processors/test_illumina.py", line 524, in test_sanitize_file_soft_example
    results = _try_sanitizing_file(contents)
  File "/home/user/tests/processors/test_illumina.py", line 100, in _try_sanitizing_file
    job_context = illumina._detect_encoding(job_context)
  File "/home/user/data_refinery_workers/processors/illumina.py", line 75, in _detect_encoding
    encoding = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'file'

======================================================================
FAIL: test_detect_columns (tests.processors.test_illumina.IlluminaToPCLTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/tests/processors/test_illumina.py", line 552, in test_detect_columns
    self.assertNotEqual(final_context.get("success"), False)
AssertionError: False == False

======================================================================
FAIL: test_good_detection (tests.processors.test_illumina.IlluminaToPCLTestCase)
GSE54661 appears to be mislabled (illuminaHumanv4) on GEO. Shows our detector works.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/tests/processors/test_illumina.py", line 214, in test_good_detection
    self.assertSucceeded(pj)
  File "/home/user/tests/utils.py", line 44, in assertSucceeded
    raise self.failureException(msg)
AssertionError: Processor job failed with reason 'Unhandled exception caught while running processor function _detect_encoding in pipeline: [Errno 2] No such file or directory: 'file''

======================================================================
FAIL: test_illumina_id_ref_column_with_whitespace (tests.processors.test_illumina.IlluminaToPCLTestCase)
This test case tests the issue brought up in
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/tests/processors/test_illumina.py", line 471, in test_illumina_id_ref_column_with_whitespace
    self.assertSucceeded(pj)
  File "/home/user/tests/utils.py", line 44, in assertSucceeded
    raise self.failureException(msg)
AssertionError: Processor job failed with reason 'Unhandled exception caught while running processor function _detect_encoding in pipeline: [Errno 2] No such file or directory: 'file''

======================================================================
FAIL: test_illumina_latin1_input (tests.processors.test_illumina.IlluminaToPCLTestCase)
Test a latin1-encoded Illumina file.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/tests/processors/test_illumina.py", line 273, in test_illumina_latin1_input
    self.assertFailed(
  File "/home/user/tests/utils.py", line 55, in assertFailed
    raise self.failureException(
AssertionError: Processor job failed, but for an incorrect reason.
We expected the reason to contain 'Encountered error in R code while running illumina.R pipeline during processing' but the actual reason was 'Unhandled exception caught while running processor function _detect_encoding in pipeline: [Errno 2] No such file or directory: 'file''

======================================================================
FAIL: test_illumina_no_pvalue (tests.processors.test_illumina.IlluminaToPCLTestCase)
This experiment should fail because it has no p-value columns, so
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/tests/processors/test_illumina.py", line 440, in test_illumina_no_pvalue
    self.assertFailed(pj, "Could not detect PValue column!")
  File "/home/user/tests/utils.py", line 55, in assertFailed
    raise self.failureException(
AssertionError: Processor job failed, but for an incorrect reason.
We expected the reason to contain 'Could not detect PValue column!' but the actual reason was 'Unhandled exception caught while running processor function _detect_encoding in pipeline: [Errno 2] No such file or directory: 'file''

======================================================================
FAIL: test_illumina_quoted_row_names (tests.processors.test_illumina.IlluminaToPCLTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/tests/processors/test_illumina.py", line 331, in test_illumina_quoted_row_names
    self.assertSucceeded(pj)
  File "/home/user/tests/utils.py", line 44, in assertSucceeded
    raise self.failureException(msg)
AssertionError: Processor job failed with reason 'Unhandled exception caught while running processor function _detect_encoding in pipeline: [Errno 2] No such file or directory: 'file''

======================================================================
FAIL: test_illumina_rows_starting_with_whitespace (tests.processors.test_illumina.IlluminaToPCLTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/tests/processors/test_illumina.py", line 381, in test_illumina_rows_starting_with_whitespace
    self.assertSucceeded(pj)
  File "/home/user/tests/utils.py", line 44, in assertSucceeded
    raise self.failureException(msg)
AssertionError: Processor job failed with reason 'Unhandled exception caught while running processor function _detect_encoding in pipeline: [Errno 2] No such file or directory: 'file''

======================================================================
FAIL: test_illumina_space_separated (tests.processors.test_illumina.IlluminaToPCLTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/tests/processors/test_illumina.py", line 406, in test_illumina_space_separated
    self.assertSucceeded(pj)
  File "/home/user/tests/utils.py", line 44, in assertSucceeded
    raise self.failureException(msg)
AssertionError: Processor job failed with reason 'Unhandled exception caught while running processor function _detect_encoding in pipeline: [Errno 2] No such file or directory: 'file''

======================================================================
FAIL: test_illumina_to_pcl (tests.processors.test_illumina.IlluminaToPCLTestCase)
Most basic Illumina to PCL test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/tests/processors/test_illumina.py", line 172, in test_illumina_to_pcl
    self.assertSucceeded(job)
  File "/home/user/tests/utils.py", line 44, in assertSucceeded
    raise self.failureException(msg)
AssertionError: Processor job failed with reason 'Unhandled exception caught while running processor function _detect_encoding in pipeline: [Errno 2] No such file or directory: 'file''

----------------------------------------------------------------------
Ran 14 tests in 0.639s

FAILED (failures=9, errors=4)
```

### Solution or next step

Resolve Errno 2 exception.

**Comment by arkid15r** [comment]
Fixed in https://github.com/AlexsLemonade/refinebio/pull/3239
