### ISSUE TITLE
Fix test_smasher AssertionError: Processor job failed, but for an incorrect reason issue

### ISSUE THREAD

**Issue by arkid15r** [AlexsLemonade/refinebio#3212]
### Context

In order to restore staging/prod deploy process CI/CD tests need to be fixed.

### Problem or idea

```
======================================================================
FAIL: test_create_compendia (tests.processors.test_compendia.CompendiaTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/tests/processors/test_compendia.py", line 149, in test_create_compendia
    self.assertFailed(job, "k must be between 1 and min(A.shape)")
  File "/home/user/tests/utils.py", line 55, in assertFailed
    raise self.failureException(
AssertionError: Processor job failed, but for an incorrect reason.
We expected the reason to contain 'k must be between 1 and min(A.shape)' but the actual reason was 'Unhandled exception caught while running processor function _run_iterativesvd in pipeline: `k` must be an integer satisfying `0 < k < min(A.shape)`.'
```

### Solution or next step

Resolve AssertionError.

**Comment by arkid15r** [comment]
Fixed in https://github.com/AlexsLemonade/refinebio/pull/3233
