### ISSUE TITLE
Fix test_affy_agilent "Function found when exporting methods from the namespace ‘XVector’ which is not S4 generic: ‘endoapply’" error

### ISSUE THREAD

**Issue by arkid15r** [AlexsLemonade/refinebio#3219]
### Context

In order to restore staging/prod deploy process CI/CD tests need to be fixed.

### Problem or idea

```
R[write to console]: Error: Function found when exporting methods from the namespace ‘XVector’ which is not S4 generic: ‘endoapply’

2023-02-24 19:34:19,676 local data_refinery_workers.processors.array_express ERROR [processor_job: 1]: Encountered error in R code while running AFFY_TO_PCL pipeline during processing of /home/user/data_store/raw/TEST/CEL/GSM1426071_CD_colon_active_1.CEL: Error: Function found when exporting methods from the namespace ‘XVector’ which is not S4 generic: ‘endoapply’

2023-02-24 19:34:19,677 local data_refinery_workers.processors.utils ERROR [failure_reason: Encountered error in R code while running AFFY_TO_PCL pipeline during processing of /home/user/data_store/raw/TEST/CEL/GSM1426071_CD_colon_active_1.CEL: Error: Function found when exporting methods from the namespace ‘XVector’ which is not S4 generic: ‘endoapply’
] [processor_job: 1]: Processor function _run_scan_upc failed. Terminating pipeline.
2023-02-24 19:34:19,714 local data_refinery_workers.processors.utils ERROR [pipeline_applied: AFFY_TO_PCL] [failure_reason: Encountered error in R code while running AFFY_TO_PCL pipeline during processing of /home/user/data_store/raw/TEST/CEL/GSM1426071_CD_colon_active_1.CEL: Error: Function found when exporting methods from the namespace ‘XVector’ which is not S4 generic: ‘endoapply’
] [processor_job: 1] [no_retry: True]: Processor job failed!
F2023-02-24 19:34:19,768 local data_refinery_workers.processors.utils DEBUG [pipeline: AFFY_TO_PCL] [processor_job: 2]: Starting processor Job.
R[write to console]: Error: Function found when exporting methods from the namespace ‘XVector’ which is not S4 generic: ‘endoapply’

2023-02-24 19:34:22,367 local data_refinery_workers.processors.array_express ERROR [processor_job: 2]: Encountered error in R code while running AFFY_TO_PCL pipeline during processing of /home/user/data_store/raw/TEST/CEL/GSM1364667_U_110208_7-02-10_S2.CEL: Error: Function found when exporting methods from the namespace ‘XVector’ which is not S4 generic: ‘endoapply’

2023-02-24 19:34:22,368 local data_refinery_workers.processors.utils ERROR [failure_reason: Encountered error in R code while running AFFY_TO_PCL pipeline during processing of /home/user/data_store/raw/TEST/CEL/GSM1364667_U_110208_7-02-10_S2.CEL: Error: Function found when exporting methods from the namespace ‘XVector’ which is not S4 generic: ‘endoapply’
] [processor_job: 2]: Processor function _run_scan_upc failed. Terminating pipeline.
2023-02-24 19:34:22,402 local data_refinery_workers.processors.utils ERROR [pipeline_applied: AFFY_TO_PCL] [failure_reason: Encountered error in R code while running AFFY_TO_PCL pipeline during processing of /home/user/data_store/raw/TEST/CEL/GSM1364667_U_110208_7-02-10_S2.CEL: Error: Function found when exporting methods from the namespace ‘XVector’ which is not S4 generic: ‘endoapply’
] [processor_job: 2] [no_retry: True]: Processor job failed!
F2023-02-24 19:34:22,456 local data_refinery_workers.processors.utils DEBUG [pipeline: AFFY_TO_PCL] [processor_job: 3]: Starting processor Job.
R[write to console]: Error: Function found when exporting methods from the namespace ‘XVector’ which is not S4 generic: ‘endoapply’

2023-02-24 19:34:23,464 local data_refinery_workers.processors.array_express ERROR [processor_job: 3]: Encountered error in R code while running AFFY_TO_PCL pipeline during processing of /home/user/data_store/raw/TEST/CEL/GSM45588.CEL: Error: Function found when exporting methods from the namespace ‘XVector’ which is not S4 generic: ‘endoapply’

2023-02-24 19:34:23,465 local data_refinery_workers.processors.utils ERROR [failure_reason: Encountered error in R code while running AFFY_TO_PCL pipeline during processing of /home/user/data_store/raw/TEST/CEL/GSM45588.CEL: Error: Function found when exporting methods from the namespace ‘XVector’ which is not S4 generic: ‘endoapply’
] [processor_job: 3]: Processor function _run_scan_upc failed. Terminating pipeline.
2023-02-24 19:34:23,495 local data_refinery_workers.processors.utils ERROR [pipeline_applied: AFFY_TO_PCL] [failure_reason: Encountered error in R code while running AFFY_TO_PCL pipeline during processing of /home/user/data_store/raw/TEST/CEL/GSM45588.CEL: Error: Function found when exporting methods from the namespace ‘XVector’ which is not S4 generic: ‘endoapply’
] [processor_job: 3] [no_retry: True]: Processor job failed!
F..
======================================================================
FAIL: test_affy_to_pcl (tests.processors.test_array_express.AffyToPCLTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/tests/processors/test_array_express.py", line 115, in test_affy_to_pcl
    self.assertTrue(updated_job.success)
AssertionError: False is not true

======================================================================
FAIL: test_affy_to_pcl_huex_v1 (tests.processors.test_array_express.AffyToPCLTestCase)
Special Case because there is no CDL for Huex V1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/tests/processors/test_array_express.py", line 162, in test_affy_to_pcl_huex_v1
    self.assertTrue(updated_job.success)
AssertionError: False is not true

======================================================================
FAIL: test_affy_to_pcl_no_brainarray (tests.processors.test_array_express.AffyToPCLTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/tests/processors/test_array_express.py", line 139, in test_affy_to_pcl_no_brainarray
    self.assertTrue(updated_job.success)
AssertionError: False is not true
```

### Solution or next step

Fix R exception.

**Comment by arkid15r** [comment]
Changing the R version from 3.6 to 3.4 will hopefully resolve this.

**Comment by arkid15r** [comment]
The R version downgrade to 3.4.4 resolved the issue.
