### ISSUE TITLE
Fix end to end tests

### ISSUE THREAD

**Issue by arkid15r** [AlexsLemonade/refinebio#3278]
### Context

In order to complete restoring staging deploy process the CI/CD errors need to be fixed.

### Problem or idea

```
Polling SurveyJobs. Currently waiting for job id: 129117
SurveyJob 129117 failed!
F
======================================================================
FAIL: test_all_the_things (tests.foreman.test_end_to_end.FullFlowEndToEndTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/home/user/tests/foreman/test_end_to_end.py", line 235, in test_all_the_things
    self.process_experiments()
  File "/home/user/tests/foreman/test_end_to_end.py", line 279, in process_experiments
    self.assertTrue(wait_for_job(survey_job))
  File "/usr/lib/python3.8/unittest/case.py", line 765, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 2 tests in 3422.129s

FAILED (failures=1)
Error: Process completed with exit code 1.
```

### Solution or next step
Troubleshoot and fix the end2end tests errors.

**Comment by arkid15r** [comment]
Temporary disabled in https://github.com/AlexsLemonade/refinebio/pull/3275
