### ISSUE TITLE
e2e test throws "value must be a decimal number" error

### ISSUE THREAD

**Issue by arkid15r** [AlexsLemonade/refinebio#3333]
### Context

As a part of post deployment process we run end to end tests. 

### Problem or idea
The most recent run failed w/ the following error:

```
SurveyJob 129220 failed!
F
======================================================================
FAIL: test_all_the_things (tests.foreman.test_end_to_end.FullFlowEndToEndTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/home/user/tests/foreman/test_end_to_end.py", line 235, in test_all_the_things
    self.process_experiments()
  File "/home/user/tests/foreman/test_end_to_end.py", line 279, in process_experiments
    self.assertTrue(wait_for_job(survey_job))
  File "/usr/lib/python3.8/unittest/case.py", line 765, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 2 tests in 921.220s
```
```
Traceback (most recent call last):
--
File "/home/user/data_refinery_foreman/surveyor/geo.py", line 275, in create_experiment_and_samples_from_api
sample_object = Sample.objects.get(accession_code=sample_accession_code)
File "/usr/local/lib/python3.8/dist-packages/django/db/models/manager.py", line 85, in manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 435, in get
raise self.model.DoesNotExist(
data_refinery_common.models.sample.Sample.DoesNotExist: Sample matching query does not exist.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/django/db/models/fields/__init__.py", line 1552, in to_python
return decimal.Decimal(value)
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/home/user/data_refinery_foreman/surveyor/external_source.py", line 170, in survey
experiment, samples = self.discover_experiment_and_samples()
File "/home/user/data_refinery_foreman/surveyor/geo.py", line 500, in discover_experiment_and_samples
experiment, samples = self.create_experiment_and_samples_from_api(experiment_accession_code)
File "/home/user/data_refinery_foreman/surveyor/geo.py", line 321, in create_experiment_and_samples_from_api
sample_object.save()
File "/usr/local/lib/python3.8/dist-packages/data_refinery_common/models/sample.py", line 102, in save
return super(Sample, self).save(*args, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 739, in save
self.save_base(using=using, force_insert=force_insert,
File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 776, in save_base
updated = self._save_table(
File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 881, in _save_table
results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 919, in _do_insert
return manager._insert(
File "/usr/local/lib/python3.8/dist-packages/django/db/models/manager.py", line 85, in manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 1270, in _insert
return query.get_compiler(using=using).execute_sql(returning_fields)
File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1415, in execute_sql
for sql, params in self.as_sql():
File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1358, in as_sql
value_rows = [
File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1359, in <listcomp>
[self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1359, in <listcomp>
[self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1300, in prepare_value
value = field.get_db_prep_save(value, connection=self.connection)
File "/usr/local/lib/python3.8/dist-packages/django/db/models/fields/__init__.py", line 1561, in get_db_prep_save
return connection.ops.adapt_decimalfield_value(self.to_python(value), self.max_digits, self.decimal_places)
File "/usr/local/lib/python3.8/dist-packages/django/db/models/fields/__init__.py", line 1554, in to_python
raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ['“” value must be a decimal number.']

```
### Solution or next step

Fix the decimal conversion exception.

**Comment by davidsmejia** [comment]
Closed with 3334
