### ISSUE TITLE
SRA surveyor is broken

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#612]
### Context

```
ta-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev 2018-09-12 21:07:32,247 local data_refinery_foreman.surveyor.external_source ERROR [survey_job: 695]: Excep
tion caught while discovering samples. Terminating survey job.
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev Traceback (most recent call last):
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev   File "/home/user/data_refinery_foreman/surveyor/sra.py", line 354, in _generate_experiment_and_samples
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev     experiment_object = Experiment.objects.get(accession_code=experiment_accession_code)
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev   File "/usr/local/lib/python3.5/dist-packages/django/db/models/manager.py", line 82, in manager_method
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev     return getattr(self.get_queryset(), name)(*args, **kwargs)
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev   File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 403, in get
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev     self.model._meta.object_name
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev data_refinery_common.models.models.DoesNotExist: Experiment matching query does not exist.
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev During handling of the above exception, another exception occurred:
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev Traceback (most recent call last):
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 85, in _execute
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev     return self.cursor.execute(sql, params)
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev psycopg2.DataError: invalid input syntax for type json
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev LINE 1: ...roup 4) using small RNA sequencing and RNA-seq.', 'Library p...
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev                                                              ^
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev DETAIL:  Token "Library" is invalid.
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev CONTEXT:  JSON data, line 1: Library...
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev The above exception was the direct cause of the following exception:
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev Traceback (most recent call last):
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev   File "/home/user/data_refinery_foreman/surveyor/external_source.py", line 167, in survey
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev     experiment, samples = self.discover_experiment_and_samples()
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev   File "/home/user/data_refinery_foreman/surveyor/sra.py", line 551, in discover_experiment_and_samples
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev     returned_experiment, samples = self._generate_experiment_and_samples(run_id)
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev   File "/home/user/data_refinery_foreman/surveyor/sra.py", line 397, in _generate_experiment_and_samples
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev     experiment_object.save()
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev   File "/usr/local/lib/python3.5/dist-packages/data_refinery_common/models/models.py", line 283, in save
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev     return super(Experiment, self).save(*args, **kwargs)
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev   File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 729, in save
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev     force_update=force_update, update_fields=update_fields)
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev   File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 759, in save_base
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev     updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev   File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 842, in _save_table
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev   File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 880, in _do_insert
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev     using=using, raw=raw)
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev   File "/usr/local/lib/python3.5/dist-packages/django/db/models/manager.py", line 82, in manager_method
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev     return getattr(self.get_queryset(), name)(*args, **kwargs)
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev   File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 1125, in _insert
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev     return query.get_compiler(using=using).execute_sql(return_id)
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev   File "/usr/local/lib/python3.5/dist-packages/django/db/models/sql/compiler.py", line 1280, in execute_sql
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev     cursor.execute(sql, params)
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev   File "/usr/local/lib/python3.5/dist-packages/raven/contrib/django/client.py", line 127, in execute
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev     return real_execute(self, sql, params)
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 68, in execute
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 77, in _execute_with_wrap
pers
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev     return executor(sql, params, many, context)
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 85, in _execute
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev     return self.cursor.execute(sql, params)
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev   File "/usr/local/lib/python3.5/dist-packages/django/db/utils.py", line 89, in __exit__
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev     raise dj_exc_value.with_traceback(traceback) from exc_value
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 85, in _execute
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev     return self.cursor.execute(sql, params)
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev django.db.utils.DataError: invalid input syntax for type json
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev LINE 1: ...roup 4) using small RNA sequencing and RNA-seq.', 'Library p...
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev                                                              ^
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev DETAIL:  Token "Library" is invalid.
data-refinery-log-group-kurtwheeler-dev log-stream-surveyor-docker-kurtwheeler-dev CONTEXT:  JSON data, line 1: Library...
```

### Problem or idea

https://github.com/AlexsLemonade/refinebio/pull/587 changed `experiment.protocol_description` to be a JSON field but it did not do anything to data going into the field. Therefore it's now just trying to write plain text that comes out of an XML file into a JSON field.

### Solution or next step

I'm not actually sure. Why was `experiment.protocol_description` made a JSON field? Should it  be a JSON field? If so how is the data going into it supposed to be formatted?

cc @dongbohu 

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by dongbohu** [comment]
The main reason why `protocol_description` in `Experiment` model is changed from plain text to JSONField is to collect the detailed protocol information for Array Express experiment. Here is an example:
https://www.ebi.ac.uk/arrayexpress/json/v3/experiments/E-MEXP-31/protocols

According to Django doc:
https://docs.djangoproject.com/en/2.1/ref/contrib/postgres/fields/#django.contrib.postgres.fields.JSONField
`string` is a valid type for this type of field:
```
In Python the data is represented in its Python native format: 
dictionaries, lists, strings, numbers, booleans and None.
```

**Comment by kurtwheeler** [comment]
This seems to have been the cause of failure for all 97 experiments that were surveyed before I stopped the survey_dispatcher, although I didn't check the logs exhaustively to make 100% sure. However it's definitely not just a bad sample or a one-off error.

**Comment by kurtwheeler** [comment]
I'm open to other explanations of why this failed. This happened in my dev stack, so anyone can pull the logs with `awslogs` and also connect to the client instance that's up in that stack to poke around the DB. I'll be focusing on debugging this this morning since it's blocking our crunch progress, but additional eyes might help figure it out sooner.

**Comment by dongbohu** [comment]
@kurtwheeler Do you have any of the 97 experiment's accession code? I would like to test the SRA surveyor from my desktop.

**Comment by kurtwheeler** [comment]
Yes I was able to track down SRP095882 as one of them. It's definitely reproducible locally.

**Comment by dongbohu** [comment]
I wrote a small test on my desktop and it failed due to the exception raised on lines 87-88 of `sra.py`:
```
        if metadata["library_strategy"] != "RNA-Seq":
            raise UnsupportedDataTypeError("library_strategy not RNA-Seq.")
```
because the value of `metadata["library_strategy"]` is `miRNA-Seq`, does this mean anything to you?

**Comment by kurtwheeler** [comment]
Ok, this may have been a false alarm. I have pulled dev into the ncbisra branch and now I can no longer reproduce. I think this may have been caused by migrations changing in some weird way... perhaps the migrations that were run on the database didn't match what Django thought the data model was? I'm going to redeploy with the latest pull and see what happens.

(For the record I got the same failure as you did. That's an expected failure that will happen when it's not the right kind of data. We want the library-strategy to be RNA-Seq.)

Sorry about all this!

**Comment by dongbohu** [comment]
No problem. Please let me know if you need any help.

**Comment by Miserlou** [comment]
I also think this is causing build errors: https://circleci.com/gh/AlexsLemonade/refinebio/6972?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by kurtwheeler** [comment]
Closed by https://github.com/AlexsLemonade/refinebio/pull/620
