### ISSUE TITLE
`pandas._libs.ops.scalar_compare` QN Error for Some Samples

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio#614]
### Context

During DR QN, there are some errors in the form:

```
2018-09-13 14:55:43,436 i-06a6ad87904d9c47d data_refinery_workers.processors.smasher ERROR [dataset_id: d4226cf4-370e-4df6-9b7d-4ca6cc66c914] [file: /home/user/data_store/smashed/d4226cf4-370e-4df6-9b7d-4ca6cc66c914/gene_converted_GSM102671-tbl-1.txt]: Unable to smash file
Traceback (most recent call last):
  File "/home/user/data_refinery_workers/processors/smasher.py", line 150, in _smash
    if (not computed_file_path.endswith("lengthScaledTPM.tsv")) and (data.max() > 100).any():
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/ops.py", line 1283, in wrapper
    res = na_op(values, other)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/ops.py", line 1143, in na_op
    result = _comp_method_OBJECT_ARRAY(op, x, y)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/ops.py", line 1122, in _comp_method_OBJECT_ARRAY
    result = libops.scalar_compare(x, y, op)
  File "pandas/_libs/ops.pyx", line 98, in pandas._libs.ops.scalar_compare
TypeError: unorderable types: str() > int()
```

This is only happening for files in the form `gene_converted_GSM102671-tbl-1.txt`, but not for files in the form `GSM2970800_IC_2_dieldrin_Zebrafish_.PCL`.

My initial guess looking at similar files is that this is the result of a missing header row on the `gene_conterted` files (_sometimes_). We should add a check, ideally at both write time and smashtime.

**Comment by Miserlou** [comment]
[glqgogn4_gene_converted_GSM102671-tbl-1.txt](https://github.com/AlexsLemonade/refinebio/files/2380406/glqgogn4_gene_converted_GSM102671-tbl-1.txt)

**Comment by Miserlou** [comment]
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM102671

ABS_CALL?

**Comment by Miserlou** [comment]
Discussion result:

a) Make sure QN only takes samples that we have processed from raw (not gene converted)
b) If you've got more columns than we expect after NO_OP, GTFO.
