### ISSUE TITLE
File Not Found During SHA1 Check

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio#681]
### Context
```
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod 2018-09-30 09:53:19,387 i-03b2b1628573bd053 data_refinery_workers.processors.utils ERROR [processor_job: 6648] [no_retry: False]: Unhandled exception caught while running processor function _run_salmon in pipeline:
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod Traceback (most recent call last):
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod   File "/home/user/data_refinery_workers/processors/utils.py", line 231, in run_pipeline
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod     last_result = processor(last_result)
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod   File "/home/user/data_refinery_workers/processors/salmon.py", line 675, in _run_salmon
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod     quant_file.calculate_sha1()
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/data_refinery_common/models/models.py", line 759, in calculate_sha1
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod     with open(self.absolute_file_path, mode='rb') as open_file:
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod FileNotFoundError: [Errno 2] No such file or directory: '/home/user/data_store/processor_job_6648/SRR6025586_output/quant.sf'
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod 2018-09-30 09:53:25,258 i-03b2b1628573bd053 data_refinery_workers.processors.utils ERROR [failure_reason: Unhandled exception caught while running processor function _run_salmon in pipeline: [Errno 2] No such file or directory: '/home/user/data_store/processor_job_6648/SRR6025586_output/quant.sf'] [pipeline_applied: SALMON] [processor_job: 6648] [no_retry: False]: Processor job failed!
```

### Problem or idea

This actually seems like a fairly common error, and I can't immediately explain it. 

My guesses are:

1) Salmon isn't creating the final result file, but isn't reporting the proper error code/stderr, so we never see the failure and just assume the file was created.
2) There is a disk read problem which happens when we try to read in the file for hashing.

### Solution or next step

Investigate and try to repro with `SRR6025586`.

**Comment by Miserlou** [comment]
This error only occurred in the Salmon pipeline, so I'm thinking it's the first.

**Comment by jaclyn-taroni** [comment]
This is one of five tickets identified at the beginning of last sprint as "may already be solved" -- what is the status on this?
