### ISSUE TITLE
KeyError: 'internal_accession'

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio#682]
This one (these ones) look like a straight-up bug. Possible we couldn't actually ever process this sample anyway since we can't determine the internal accession, but we should still handle this more gracefully.

```
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod 2018-09-30 07:26:10,564 i-094075f4b46b5ec64 data_refinery_workers.processors.utils ERROR [processor_job: 10329] [no_retry: True]: Unhandled exception caught while running processor function _convert_genes in pipeline:
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod Traceback (most recent call last):
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod   File "/home/user/data_refinery_workers/processors/utils.py", line 231, in run_pipeline
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod     last_result = processor(last_result)
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod   File "/home/user/data_refinery_workers/processors/no_op.py", line 158, in _convert_genes
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod     return _convert_affy_genes(job_context)
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod   File "/home/user/data_refinery_workers/processors/no_op.py", line 163, in _convert_affy_genes
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod     gene_index_path = "/home/user/gene_indexes/" + job_context["internal_accession"] + ".tsv.gz"
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod KeyError: 'internal_accession'
data-refinery-log-group-circleci-prod log-stream-processor-docker-circleci-prod 2018-09-30 07:26:10,586 i-094075f4b46b5ec64 data_refinery_workers.processors.utils ERROR [processor_job: 10329] [pipeline_applied: NO_OP] [no_retry: True] [failure_reason: Unhandled exception caught while running processor function _convert_genes in pipeline: 'internal_accession']: Processor job failed!
```

**Comment by jaclyn-taroni** [comment]
This is one of five tickets identified at the beginning of last sprint as "may already be solved" -- what is the status on this?
