### ISSUE TITLE
Foreman can't re-queue any jobs because of the database connection closing

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#789]
### Context

The Foreman logs are full of this:
```
2018-11-07 20:02:40,247 i-0d4a6a561fd82091c data_refinery_foreman.foreman.main ERROR: Exception caught by Foreman while running retry_hung_survey_jobs
 Traceback (most recent call last):
   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/base.py", line 234, in _cursor
     return self._prepare_cursor(self.create_cursor(name))
   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/postgresql/base.py", line 222, in create_cursor
     cursor = self.connection.cursor()
 psycopg2.InterfaceError: connection already closed
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/home/user/data_refinery_foreman/foreman/main.py", line 65, in wrapper
     function(*args, **kwargs)
   File "/home/user/data_refinery_foreman/foreman/main.py", line 508, in retry_hung_survey_jobs
     for job in potentially_hung_jobs:
   File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 268, in __iter__
     self._fetch_all()
   File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 1186, in _fetch_all
     self._result_cache = list(self._iterable_class(self))
   File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 54, in __iter__
     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
   File "/usr/local/lib/python3.5/dist-packages/django/db/models/sql/compiler.py", line 1063, in execute_sql
     cursor = self.connection.cursor()
   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/base.py", line 255, in cursor
     return self._cursor()
   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/base.py", line 234, in _cursor
     return self._prepare_cursor(self.create_cursor(name))
   File "/usr/local/lib/python3.5/dist-packages/django/db/utils.py", line 89, in __exit__
     raise dj_exc_value.with_traceback(traceback) from exc_value
   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/base.py", line 234, in _cursor
     return self._prepare_cursor(self.create_cursor(name))
   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/postgresql/base.py", line 222, in create_cursor
     cursor = self.connection.cursor()
 django.db.utils.InterfaceError: connection already closed
```

### Problem or idea

I am not sure what is going on, but there are >40k downloader jobs that need to be requeued (they hit their retry limit because of getting cancelled and requeued too many times before we added a fix to prevent that issue). None of them are getting requeued because of that error, so we aren't processing much.

### Solution or next step

I am not yet sure what the solution is, but we gotta get the Foreman back up and running so we can requeue the work and process lots of stuff!

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by kurtwheeler** [comment]
Closed by #790
