### ISSUE TITLE
Foreman database connection broke overnight causing things to stop working

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#902]
### Context

Foreman logs this morning were full of:
```
data-refinery-log-group-circleci-prod log-stream-foreman-circleci-prod 2018-12-07 15:26:21,351 i-0277d8159091c4549 [volume: -1] data_refinery_foreman.foreman.main ERROR: Exception caught by Foreman while running
 retry_lost_downloader_jobs
data-refinery-log-group-circleci-prod log-stream-foreman-circleci-prod Traceback (most recent call last):
data-refinery-log-group-circleci-prod log-stream-foreman-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/base.py", line 234, in _cursor
data-refinery-log-group-circleci-prod log-stream-foreman-circleci-prod     return self._prepare_cursor(self.create_cursor(name))
data-refinery-log-group-circleci-prod log-stream-foreman-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/postgresql/base.py", line 222, in create_cursor
data-refinery-log-group-circleci-prod log-stream-foreman-circleci-prod     cursor = self.connection.cursor()
data-refinery-log-group-circleci-prod log-stream-foreman-circleci-prod psycopg2.InterfaceError: connection already closed
data-refinery-log-group-circleci-prod log-stream-foreman-circleci-prod 
data-refinery-log-group-circleci-prod log-stream-foreman-circleci-prod The above exception was the direct cause of the following exception:
data-refinery-log-group-circleci-prod log-stream-foreman-circleci-prod 
data-refinery-log-group-circleci-prod log-stream-foreman-circleci-prod Traceback (most recent call last):
data-refinery-log-group-circleci-prod log-stream-foreman-circleci-prod   File "/home/user/data_refinery_foreman/foreman/main.py", line 99, in wrapper
data-refinery-log-group-circleci-prod log-stream-foreman-circleci-prod     function(*args, **kwargs)
data-refinery-log-group-circleci-prod log-stream-foreman-circleci-prod   File "/home/user/data_refinery_foreman/foreman/main.py", line 424, in retry_lost_downloader_jobs
data-refinery-log-group-circleci-prod log-stream-foreman-circleci-prod     for job in potentially_lost_jobs:
data-refinery-log-group-circleci-prod log-stream-foreman-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 268, in __iter__
data-refinery-log-group-circleci-prod log-stream-foreman-circleci-prod     self._fetch_all()
data-refinery-log-group-circleci-prod log-stream-foreman-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 1186, in _fetch_all
data-refinery-log-group-circleci-prod log-stream-foreman-circleci-prod     self._result_cache = list(self._iterable_class(self))
data-refinery-log-group-circleci-prod log-stream-foreman-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 54, in __iter__
data-refinery-log-group-circleci-prod log-stream-foreman-circleci-prod     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
data-refinery-log-group-circleci-prod log-stream-foreman-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/models/sql/compiler.py", line 1063, in execute_sql
data-refinery-log-group-circleci-prod log-stream-foreman-circleci-prod     cursor = self.connection.cursor()
data-refinery-log-group-circleci-prod log-stream-foreman-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/base.py", line 255, in cursor
data-refinery-log-group-circleci-prod log-stream-foreman-circleci-prod     return self._cursor()
data-refinery-log-group-circleci-prod log-stream-foreman-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/base.py", line 234, in _cursor
data-refinery-log-group-circleci-prod log-stream-foreman-circleci-prod     return self._prepare_cursor(self.create_cursor(name))
data-refinery-log-group-circleci-prod log-stream-foreman-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/utils.py", line 89, in __exit__
data-refinery-log-group-circleci-prod log-stream-foreman-circleci-prod     raise dj_exc_value.with_traceback(traceback) from exc_value
data-refinery-log-group-circleci-prod log-stream-foreman-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/base.py", line 234, in _cursor
data-refinery-log-group-circleci-prod log-stream-foreman-circleci-prod     return self._prepare_cursor(self.create_cursor(name))
data-refinery-log-group-circleci-prod log-stream-foreman-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/postgresql/base.py", line 222, in create_cursor
data-refinery-log-group-circleci-prod log-stream-foreman-circleci-prod     cursor = self.connection.cursor()
data-refinery-log-group-circleci-prod log-stream-foreman-circleci-prod django.db.utils.InterfaceError: connection already closed
```

I used `docker restart` to restart the foreman container and everything picked back up.

### Problem or idea

We need to either prevent this from happening again or be able to detect when it is happening so we can restart the Foreman.

### Solution or next step

I'm not really sure. This needs to be investigated.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by kurtwheeler** [comment]
I've tried to reproduce this locally doing the following:
  * Running `./foreman/run_surveyor.sh retry_jobs` and then while that is running restarting the postgres database with `docker restart drdb`. This resulted in the foreman saying it could not connect to the database, but once it came back up it reconnected and resumed queuing jobs.
  * Once again with the foreman running, I closed the database connections wtih:
```
SELECT 
    pg_terminate_backend(pid) 
FROM 
    pg_stat_activity 
WHERE 
    -- don't kill my own connection!
    pid <> pg_backend_pid()
    -- don't kill the connections to other databases
    AND datname = 'data_refinery'
    ;
```
