### ISSUE TITLE
Survey jobs seem to be failing way too often.

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio#949]
### Context

I queued up a SURVEYOR_DISPATCHER job this morning to survey >15k microarray experiments this morning. A lot of them seem to be failing:
```
data_refinery=> select count(*) from survey_jobs where last_modified  > now() - interval '1 hours' and success='t';
 count 
-------
  1349
(1 row)

data_refinery=> select count(*) from survey_jobs where last_modified  > now() - interval '1 hours' and success='f';
 count 
-------
  3377
(1 row)
```

### Problem or idea

There seem to be a number of different errors coming up a lot:

```
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod 2018-12-19 15:42:15,608 i-0b531fb9c67d98c45 [volume: 22] data_refinery_foreman.surveyor.array_express ERROR [experiment_accession_code: E-TABM-61]: Erro
r occurred while surveying experiment!
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod Traceback (most recent call last):
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod   File "/home/user/data_refinery_foreman/surveyor/array_express.py", line 123, in create_experiment_from_api
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod     experiment_object = Experiment.objects.get(accession_code=experiment_accession_code)
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/models/manager.py", line 82, in manager_method
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod     return getattr(self.get_queryset(), name)(*args, **kwargs)
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 399, in get
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod     self.model._meta.object_name
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod data_refinery_common.models.models.Experiment.DoesNotExist: Experiment matching query does not exist.
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod During handling of the above exception, another exception occurred:
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod Traceback (most recent call last):
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 449, in send
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod     timeout=timeout
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 731, in urlopen
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod     body_pos=body_pos, **response_kw)
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 731, in urlopen
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod     body_pos=body_pos, **response_kw)
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 731, in urlopen
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod     body_pos=body_pos, **response_kw)
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 711, in urlopen
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod     retries = retries.increment(method, url, response=response, _pool=self)
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 398, in increment
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod     raise MaxRetryError(_pool, url, error or ResponseError(cause))
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.ebi.ac.uk', port=443): Max retries exceeded with url: /arrayexpress/files/E-TABM-61/E-TABM-61.idf.txt (Caused by ResponseError('too many 500 error responses',))
```

```
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod 2018-12-19 15:44:39,509 i-02b5f962f2d6a9019 [volume: 9] data_refinery_foreman.surveyor.external_source ERROR [survey_job: 102716]: Exception caught whil
e discovering samples. Terminating survey job.
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod Traceback (most recent call last):
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod   File "/home/user/data_refinery_foreman/surveyor/array_express.py", line 513, in create_samples_from_api
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod     sample_object = Sample.objects.get(accession_code=sample_accession_code)
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/models/manager.py", line 82, in manager_method
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod     return getattr(self.get_queryset(), name)(*args, **kwargs)
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 399, in get
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod     self.model._meta.object_name
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod data_refinery_common.models.models.Sample.DoesNotExist: Sample matching query does not exist.
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod During handling of the above exception, another exception occurred:
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod Traceback (most recent call last):
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 85, in _execute
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod     return self.cursor.execute(sql, params)
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod psycopg2.IntegrityError: null value in column "title" violates not-null constraint
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod DETAIL:  Failing row contains (663348, E-MIMR-2-csc.mrc.ac.uk:mimir/BioSource:BS_DPBK_04d, null, ARRAY_EXPRESS, https://www.ebi.ac.uk/arrayexpress/json/
v3/experiments/E-MIMR-2/..., , , t, mgu74av2, [MG_U74Av2] Affymetrix Murine Genome U74A Version 2 Array, MICROARRAY, AFFYMETRIX, [{"Text": "ExpressionCall", "Type": "bioassay_data_transformatio..., , null, , , , , , , , , , , f, t,
 2018-12-19 15:44:38.951692+00, 2018-12-19 15:44:38.951692+00, 51).
```

```
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod 2018-12-19 15:44:41,590 i-08237fff3b74ea8f4 [volume: 3] data_refinery_foreman.surveyor.external_source ERROR [survey_job: 102832]: Exception caught while discovering samples. Terminating survey job.
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod Traceback (most recent call last):
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod   File "/home/user/data_refinery_foreman/surveyor/array_express.py", line 513, in create_samples_from_api
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod     sample_object = Sample.objects.get(accession_code=sample_accession_code)
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/models/manager.py", line 82, in manager_method
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod     return getattr(self.get_queryset(), name)(*args, **kwargs)
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 399, in get
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod     self.model._meta.object_name
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod data_refinery_common.models.models.Sample.DoesNotExist: Sample matching query does not exist.
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod During handling of the above exception, another exception occurred:
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod Traceback (most recent call last):
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod   File "/home/user/data_refinery_foreman/surveyor/external_source.py", line 176, in survey
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod     experiment, samples = self.discover_experiment_and_samples()
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod   File "/home/user/data_refinery_foreman/surveyor/array_express.py", line 624, in discover_experiment_and_samples
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod     samples = self.create_samples_from_api(experiment, platform_dict)
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod   File "/home/user/data_refinery_foreman/surveyor/array_express.py", line 557, in create_samples_from_api
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod     harmonized_sample = harmonized_samples[title]
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod KeyError: 123890602
```

```
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod ['Exception caught while discovering samples. Terminating survey job.', '  File "data_refinery_foreman/surveyor/external_source.py", line 176, in survey
', '  File "data_refinery_foreman/surveyor/array_express.py", line 624, in discover_experiment_and_samples', '  File "data_refinery_foreman/surveyor/array_express.py", line 557, in create_samples_from_api']
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod 2018-12-19 15:43:44,597 i-0ec9e20af39ad67be [volume: 16] data_refinery_foreman.surveyor.array_express ERROR [experiment_accession_code: E-MTAB-6086]: Er
ror occurred while surveying experiment!
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod Traceback (most recent call last):
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod   File "/home/user/data_refinery_foreman/surveyor/array_express.py", line 123, in create_experiment_from_api
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod     experiment_object = Experiment.objects.get(accession_code=experiment_accession_code)
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/models/manager.py", line 82, in manager_method
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod     return getattr(self.get_queryset(), name)(*args, **kwargs)
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 399, in get
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod     self.model._meta.object_name
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod data_refinery_common.models.models.Experiment.DoesNotExist: Experiment matching query does not exist.
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod During handling of the above exception, another exception occurred:
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod Traceback (most recent call last):
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 85, in _execute
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod     return self.cursor.execute(sql, params)
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod psycopg2.DataError: value too long for type character varying(64)
```

```
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod psycopg2.DataError: value too long for type character varying(32)
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod The above exception was the direct cause of the following exception:
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod Traceback (most recent call last):
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod   File "/home/user/data_refinery_foreman/surveyor/array_express.py", line 613, in discover_experiment_and_samples
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod     experiment, platform_dict = self.create_experiment_from_api(experiment_accession_code)
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod   File "/home/user/data_refinery_foreman/surveyor/array_express.py", line 229, in create_experiment_from_api
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod     experiment_object.save()
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/data_refinery_common/models/models.py", line 302, in save
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod     return super(Experiment, self).save(*args, **kwargs)
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 718, in save
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod     force_update=force_update, update_fields=update_fields)
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 748, in save_base
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod     updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 812, in _save_table
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod     forced_update)
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 861, in _do_update
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod     return filtered._update(values) > 0
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 712, in _update
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod     return query.get_compiler(self.db).execute_sql(CURSOR)
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/models/sql/compiler.py", line 1383, in execute_sql
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod     cursor = super().execute_sql(result_type)
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/models/sql/compiler.py", line 1065, in execute_sql
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod     cursor.execute(sql, params)
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/raven/contrib/django/client.py", line 127, in execute
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod     return real_execute(self, sql, params)
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 68, in execute
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod     return executor(sql, params, many, context)
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 85, in _execute
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod     return self.cursor.execute(sql, params)
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/utils.py", line 89, in __exit__
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod     raise dj_exc_value.with_traceback(traceback) from exc_value
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 85, in _execute
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod     return self.cursor.execute(sql, params)
data-refinery-log-group-circleci-prod log-stream-surveyor-docker-circleci-prod django.db.utils.DataError: value too long for type character varying(32)
```

### Solution or next step

Some of these may be caused by us DDOSing our source databases because we're running ~500 surveyor jobs at a time. We may need to find a way to limit the number of concurrent surveyor jobs.

Some of them seem to be related to the harmonization code and missing or invalid values for the `title` or other columns.

Some of them of them seem to be a issue with our data model not having large enough fields.

We should look into these different failure types. We can also open sub-issues to deal with different error types if desired.

### New Issue Checklist

- [x] The title is short and descriptive.
- [x] You have explained the context that led you to write this issue.
- [x] You have reported a problem or idea.
- [x] You have proposed a solution or next step.

**Comment by kurtwheeler** [comment]
https://github.com/AlexsLemonade/refinebio/pull/1497 addressed this sufficiently I think.
